import os
import re
from datetime import datetime
import collections

# Stateful memory to track attacks over time
failed_logins = collections.defaultdict(int)
blocked_ips = set()

def analyze_logs(log_file):
    """Parses the log file line by line for threat signatures."""
    if not os.path.exists(log_file):
        print(f"[-] Error: Telemetry file '{log_file}' not found.")
        return

    print(f"[+] Ingesting {log_file} for indicators of compromise...\n")
    
    with open(log_file, 'r') as file:
        for line in file:
            process_telemetry(line.strip())

def process_telemetry(line):
    """Evaluates individual log entries against security rules."""
    # Expected format: TIMESTAMP | IP_ADDRESS | ACTION | HTTP_STATUS | PAYLOAD
    parts = [p.strip() for p in line.split('|')]
    if len(parts) < 5:
        return

    timestamp, ip, action, status, payload = parts
    
    # Ignore traffic from already contained threats
    if ip in blocked_ips:
        return

    # RULE 1: Detect Web Exploits (SQL Injection / XSS)
    if re.search(r"(UNION SELECT|<script>|--|1=1)", payload, re.IGNORECASE):
        trigger_mitigation(ip, f"Web Exploit Signature Detected: {payload}")
        return

    # RULE 2: Detect Brute Force Attacks
    if action == "LOGIN" and status == "401":
        failed_logins[ip] += 1
        if failed_logins[ip] >= 5:
            trigger_mitigation(ip, "Authentication Brute-Force Threshold Exceeded (>4 attempts)")

def trigger_mitigation(ip, reason):
    """Executes automated defensive measures and reporting."""
    print(f"[!] CRITICAL THREAT DETECTED: Source {ip}")
    print(f" [*] Trigger: {reason}")
    print(f" [+] Executing automated firewall mitigation...")
    
    # Generate the firewall command that would isolate the host
    firewall_cmd = f"iptables -A INPUT -s {ip} -j DROP"
    print(f"     -> Running: {firewall_cmd}")
    
    blocked_ips.add(ip)
    generate_incident_report(ip, reason, firewall_cmd)

def generate_incident_report(ip, reason, mitigation_cmd):
    """Creates a professional Markdown incident response ledger."""
    filename = f"incident_report_{ip.replace('.', '_')}.md"
    
    with open(filename, 'w') as f:
        f.write(f"# Incident Response Automated Triage\n")
        f.write(f"**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"**Target Threat IP:** {ip}\n\n")
        f.write(f"## Threat Assessment\n{reason}\n\n")
        f.write(f"## Automated Containment Executed\n")
        f.write(f"The following network filter was applied to secure the host:\n")
        f.write(f"```bash\n{mitigation_cmd}\n```\n")
        
    print(f" [+] Triage ledger exported to: {filename}\n")

if __name__ == "__main__":
    # Point the engine at the log file generated by our Bash script
    analyze_logs("server_telemetry.log")